name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Android SDK
        run: |
          # local.properties 파일을 생성하고 Google API 키를 설정
          echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties
          echo "google.api.key=${{ secrets.GOOGLE_API_KEY }}" >> local.properties
          
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      - name: Install dependencies and build
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
