name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Android SDK
        run: |
          # local.properties 파일을 생성하고 Google API 키를 설정
          echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties
          echo "google.api.key=${{ secrets.GOOGLE_API_KEY }}" >> local.properties

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'           # 사용할 Java 버전
          distribution: 'temurin'      # AdoptOpenJDK 대신 Temurin을 사용
          java-package: jdk            # JDK를 설치

      - name: Install Android SDK dependencies
        run: |
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "tools"

      - name: Install dependencies and build
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
